##Creating a Kubernetes deployment to orchestrate the application container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncesync-app
  namespace: oncesync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oncesync-app
  template:
    metadata:
      labels:
        app: oncesync-app
    spec:
      containers:
      - name: oncesync-app
        image: "{{ image_id }}"
        resources:
          limits:
            memory: "10Mi"
            cpu: "30m"
        command: ["node"]
        args:
          - "index.js"
        ports:
        - containerPort: 3000
