apiVersion: v1
kind: Service
metadata:
  name: oncesync-svc
spec:
  selector:
    app: oncesync-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 
    nodePort: 3000
    targetPort: 3000
