apiVersion: v1
kind: Service
metadata:
  name: oncesync-svc
  namespace: oncesync
spec:
  selector:
    app: oncesync-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 32200
    targetPort: 3000
  externalIPs:
    - 192.168.49.2
